// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tombola.Coffee.WebApi.Data;

#nullable disable

namespace Tombola.Coffee.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Tombola.Coffee.WebApi.Entities.Bean", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Beans");

                    b.HasData(
                        new
                        {
                            Id = "66a374596122a40616cb8599",
                            Colour = "dark roast",
                            Cost = 39.26m,
                            Country = "Peru",
                            Description = "Ipsum cupidatat nisi do elit veniam Lorem magna. Ullamco qui exercitation fugiat pariatur sunt dolore Lorem magna magna pariatur minim. Officia amet incididunt ad proident. Dolore est irure ex fugiat. Voluptate sunt qui ut irure commodo excepteur enim labore incididunt quis duis. Velit anim amet tempor ut labore sint deserunt.\r\n",
                            Image = "https://images.unsplash.com/photo-1672306319681-7b6d7ef349cf",
                            Name = "TURNABOUT"
                        },
                        new
                        {
                            Id = "66a374591a995a2b48761408",
                            Colour = "golden",
                            Cost = 18.57m,
                            Country = "Vietnam",
                            Description = "Dolor fugiat duis dolore ut occaecat. Excepteur nostrud velit aute dolore sint labore do eu amet. Anim adipisicing quis ut excepteur tempor magna reprehenderit non ut excepteur minim. Anim dolore eiusmod nisi nulla aliquip aliqua occaecat.\r\n",
                            Image = "https://images.unsplash.com/photo-1641399756770-9b0b104e67c1",
                            Name = "ISONUS"
                        },
                        new
                        {
                            Id = "66a374593ae6cb5148781b9b",
                            Colour = "green",
                            Cost = 33.87m,
                            Country = "Colombia",
                            Description = "Cillum nostrud mollit non ad dolore ad dolore veniam. Adipisicing anim commodo fugiat aute commodo occaecat officia id officia ullamco. Dolore irure magna aliqua fugiat incididunt ullamco ea. Aliqua eu pariatur cupidatat ut.\r\n",
                            Image = "https://images.unsplash.com/photo-1522809269485-981d0c303355",
                            Name = "ZILLAN"
                        },
                        new
                        {
                            Id = "66a37459771606d916a226ff",
                            Colour = "dark roast",
                            Cost = 17.69m,
                            Country = "Brazil",
                            Description = "Et deserunt nisi in anim cillum sint voluptate proident. Est occaecat id cupidatat cupidatat ex veniam irure veniam pariatur excepteur duis labore occaecat amet. Culpa adipisicing nisi esse consequat adipisicing anim. Fugiat tempor enim ullamco sint anim qui enim. Voluptate duis proident reprehenderit et duis nisi. In consectetur nisi eu cupidatat voluptate ullamco nulla esse cupidatat dolore sit. Cupidatat laboris adipisicing ullamco mollit culpa cupidatat ex laborum consectetur consectetur.\r\n",
                            Image = "https://images.unsplash.com/photo-1598198192305-46b0805890d3",
                            Name = "RONBERT"
                        },
                        new
                        {
                            Id = "66a3745945fcae53593c42e7",
                            Colour = "green",
                            Cost = 26.53m,
                            Country = "Vietnam",
                            Description = "Labore veniam amet ipsum eu dolor. Aliquip Lorem et eiusmod exercitation. Amet ex eu deserunt labore est ex consectetur ut fugiat. Duis veniam voluptate elit consequat tempor nostrud enim mollit occaecat.\r\n",
                            Image = "https://images.unsplash.com/photo-1512568400610-62da28bc8a13",
                            Name = "EARWAX"
                        },
                        new
                        {
                            Id = "66a37459591e872ce11c3b41",
                            Colour = "light roast",
                            Cost = 36.56m,
                            Country = "Vietnam",
                            Description = "Reprehenderit est laboris tempor quis exercitation laboris. Aute nulla aliqua consectetur nostrud ullamco cupidatat do cillum amet reprehenderit mollit non voluptate. Deserunt consectetur reprehenderit nostrud enim proident ea. Quis quis voluptate ex dolore non reprehenderit minim veniam nisi aute do incididunt voluptate. Duis aliquip commodo cupidatat anim ut ullamco eiusmod culpa velit incididunt.\r\n",
                            Image = "https://images.unsplash.com/photo-1692299108834-038511803008",
                            Name = "EVENTEX"
                        },
                        new
                        {
                            Id = "66a374599018ca32d01fee66",
                            Colour = "green",
                            Cost = 22.92m,
                            Country = "Brazil",
                            Description = "Mollit deserunt tempor qui consectetur excepteur non. Laborum voluptate voluptate laborum non magna et. Ea velit ipsum labore occaecat ea do cupidatat duis adipisicing. Ut eiusmod dolor anim et ea ea. Aliquip mollit aliqua nisi velit consequat nisi. Laborum velit anim non incididunt non qui commodo. Ea voluptate dolore pariatur eu enim.\r\n",
                            Image = "https://images.unsplash.com/photo-1692296115158-38194aafa7df",
                            Name = "NITRACYR"
                        },
                        new
                        {
                            Id = "66a37459cca42ce9e15676a3",
                            Colour = "medium roast",
                            Cost = 37.91m,
                            Country = "Colombia",
                            Description = "Veniam laborum consequat minim laborum mollit id ea Lorem in. Labore aliqua dolore quis sunt aliquip commodo aute excepteur. Voluptate tempor consequat pariatur do esse consectetur sunt ut mollit magna enim.\r\n",
                            Image = "https://images.unsplash.com/photo-1522120378538-41fb9564bc75",
                            Name = "PARAGONIA"
                        },
                        new
                        {
                            Id = "66a374590abf949489fb28f7",
                            Colour = "golden",
                            Cost = 17.59m,
                            Country = "Colombia",
                            Description = "Commodo veniam voluptate elit reprehenderit incididunt. Ut laboris dolor sint cupidatat ut adipisicing. Nostrud magna labore voluptate commodo in sunt proident sunt deserunt dolor ullamco officia tempor dolor. Laboris exercitation est mollit eiusmod nostrud. Sit qui ullamco minim cillum officia irure cillum tempor eu. Et cupidatat proident amet dolore non minim.\r\n",
                            Image = "https://images.unsplash.com/photo-1442550528053-c431ecb55509",
                            Name = "XLEEN"
                        },
                        new
                        {
                            Id = "66a374593a88b14d9fff0e2e",
                            Colour = "green",
                            Cost = 25.49m,
                            Country = "Vietnam",
                            Description = "Deserunt consequat ea incididunt aliquip. Occaecat excepteur minim occaecat aute amet adipisicing. Tempor id veniam ipsum et tempor pariatur anim elit laboris commodo mollit. Ipsum incididunt Lorem veniam id fugiat incididunt consequat est et. Id deserunt eiusmod esse duis cupidatat Lorem. Ullamco Lorem ullamco cupidatat nostrud amet id minim ut voluptate adipisicing ipsum. Fugiat reprehenderit laborum proident eiusmod esse sint adipisicing fugiat ex.\r\n",
                            Image = "https://images.unsplash.com/photo-1549420751-ea3f7ab42006",
                            Name = "LOCAZONE"
                        },
                        new
                        {
                            Id = "66a37459b7933d86991ce243",
                            Colour = "light roast",
                            Cost = 10.27m,
                            Country = "Vietnam",
                            Description = "Qui deserunt adipisicing nulla ad enim commodo reprehenderit id veniam consequat ut do ea officia. Incididunt ex esse cupidatat consequat. Sit incididunt ex magna sint reprehenderit id minim non.\r\n",
                            Image = "https://images.unsplash.com/photo-1508690207469-5c5aebedf76d",
                            Name = "ZYTRAC"
                        },
                        new
                        {
                            Id = "66a374592169e1bfcca2fb1c",
                            Colour = "medium roast",
                            Cost = 16.44m,
                            Country = "Colombia",
                            Description = "Incididunt exercitation mollit duis consectetur consequat duis culpa tempor. Fugiat nisi fugiat dolore irure in. Fugiat nulla amet dolore labore laboris sint laborum pariatur commodo amet. Ut velit sit proident fugiat cillum cupidatat ea.\r\n",
                            Image = "https://images.unsplash.com/photo-1694763768576-0c7c3af6a4d8",
                            Name = "FUTURIS"
                        },
                        new
                        {
                            Id = "66a37459cc0f1fb1d1a24cf0",
                            Colour = "green",
                            Cost = 32.77m,
                            Country = "Peru",
                            Description = "Pariatur qui Lorem sunt labore Lorem nulla nulla ea excepteur Lorem cillum amet. Amet ea officia incididunt culpa non. Do reprehenderit qui eiusmod dolore est deserunt labore do et dolore eiusmod quis elit.\r\n",
                            Image = "https://images.unsplash.com/photo-1692299108333-471157a30882",
                            Name = "KLUGGER"
                        },
                        new
                        {
                            Id = "66a37459caf60416d0571db4",
                            Colour = "dark roast",
                            Cost = 19.07m,
                            Country = "Honduras",
                            Description = "Velit quis veniam velit et sint. Irure excepteur officia ipsum sint. Est ipsum pariatur exercitation voluptate commodo. Ex irure commodo exercitation labore nulla qui dolore ad quis.\r\n",
                            Image = "https://images.unsplash.com/photo-1673208127664-23a2f3b27921",
                            Name = "ZANITY"
                        },
                        new
                        {
                            Id = "66a3745997fa4069ce1b418f",
                            Colour = "green",
                            Cost = 29.42m,
                            Country = "Brazil",
                            Description = "Esse ad eiusmod eiusmod nisi cillum magna quis non voluptate nulla est labore in sunt. Magna aliqua pariatur commodo deserunt. Pariatur pariatur pariatur id excepteur ex elit veniam.\r\n",
                            Image = "https://images.unsplash.com/photo-1544486864-3087e2e20d91",
                            Name = "XEREX"
                        });
                });

            modelBuilder.Entity("Tombola.Coffee.WebApi.Entities.BeanOfTheDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeanId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeanId");

                    b.ToTable("BeanOfTheDays");
                });

            modelBuilder.Entity("Tombola.Coffee.WebApi.Entities.BeanOfTheDay", b =>
                {
                    b.HasOne("Tombola.Coffee.WebApi.Entities.Bean", "Bean")
                        .WithMany()
                        .HasForeignKey("BeanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bean");
                });
#pragma warning restore 612, 618
        }
    }
}
